version = 1

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"